name: SimpleServerSong
authors: [DeBe, if-Team]
version: 1.0.1
main: debe.nukkitplugin.simpleserversong.SimpleServerSong
api: [1.0.0]
website: "https://github.com/if-Team/Nukkit-Plugins/SimpleServerSong"

depend: [NoteSongAPI]