name: SkinStealer
authors: [DeBe, if-Team]
version: 1.0.1
main: debe.nukkitplugin.skinstealer.SkinStealer
api: [1.0.0]
website: "https://github.com/if-Team/Nukkit-Plugins/tree/master/SkinStealer"